import { useMemo, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, Eyebrow, Field, Header, Heading, Notice, Page } from '@/components/ui';
import { C } from '@/constants/theme';
import { payDemoSplit } from '@/services/wallet';

export default function SplitScreen() {
  const [expense, setExpense] = useState(''); const [total, setTotal] = useState(''); const [people, setPeople] = useState(['You']); const [person, setPerson] = useState(''); const [note, setNote] = useState(''); const [created, setCreated] = useState(false); const [paying, setPaying] = useState(false); const [payment, setPayment] = useState(''); const [paymentError, setPaymentError] = useState(false);
  const amount = Number(total); const each = useMemo(() => Number.isFinite(amount) && amount > 0 && people.length ? amount / people.length : null, [amount, people.length]);
  const valid = Boolean(expense.trim() && each !== null && people.length >= 2);
  async function settleDemoShare() { if (!valid) return; setPaying(true); setPayment(''); setPaymentError(false); try { const result = await payDemoSplit({ total, participant_count: people.length, expense: expense.trim() }); setPayment(`Paid ${result.each} Demo RLUSD from your simulated balance. ${result.balance} remains.`); } catch (error) { setPaymentError(true); setPayment(error instanceof Error ? error.message : 'The demo split could not be paid.'); } finally { setPaying(false); } }
  return <Page><Header title="Split an expense" /><Eyebrow>CHATNYC SPLIT</Eyebrow><Heading small>Make it even.</Heading><Text style={{ color: C.muted, fontSize: 15, lineHeight: 22 }}>Split dinner, tickets, rides, or anything else with your group.</Text><Card><Field label="EXPENSE" value={expense} onChangeText={(value) => { setExpense(value); setCreated(false); setPayment(''); }} placeholder="Dinner at…" /><Field label="TOTAL" value={total} onChangeText={(value) => { setTotal(value); setCreated(false); setPayment(''); }} placeholder="$0.00" keyboardType="decimal-pad" /><View style={{ gap: 9 }}><Text style={{ color: C.ink, fontWeight: '800' }}>PEOPLE · {people.length}</Text><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{people.map((name, index) => <Pressable accessibilityRole={index > 0 ? 'button' : undefined} accessibilityLabel={index > 0 ? `Remove ${name}` : undefined} disabled={index === 0} key={`${name}-${index}`} onPress={() => { setPeople((current) => current.filter((_, personIndex) => personIndex !== index)); setCreated(false); setPayment(''); }} style={{ minHeight: 40, justifyContent: 'center', paddingHorizontal: 12, backgroundColor: index === 0 ? '#eaf0fd' : C.soft, borderRadius: 20 }}><Text style={{ color: index === 0 ? C.blue : C.ink, fontWeight: '700' }}>{name}{index > 0 ? '  ×' : ''}</Text></Pressable>)}</View><Field label="ADD A PERSON" value={person} onChangeText={setPerson} placeholder="Name" /><Button title="Add person" secondary disabled={!person.trim()} onPress={() => { setPeople((old) => [...old, person.trim()]); setPerson(''); setCreated(false); setPayment(''); }} /></View><Field label="OPTIONAL NOTE" value={note} onChangeText={setNote} placeholder="Add a note" multiline /></Card>
    <Card><Eyebrow>YOUR SPLIT</Eyebrow><Line label="Total" value={Number.isFinite(amount) && amount > 0 ? `$${amount.toFixed(2)}` : '—'} /><Line label="People" value={String(people.length)} /><Line label="Each" value={each === null ? '—' : `$${each.toFixed(2)}`} strong /></Card>
    {created ? <Notice>Split preview created · {each === null ? '—' : `$${each.toFixed(2)} per person`}. No payment has been made.</Notice> : null}
    {payment ? <Notice error={paymentError}>{payment}</Notice> : null}
    <Button title="Create split preview" disabled={!valid} onPress={() => { setCreated(true); setPayment(''); setPaymentError(false); }} />{created ? <Button title={paying ? 'Paying demo share…' : payment && !paymentError ? 'Demo share paid' : 'Pay my share with Demo RLUSD'} secondary disabled={paying || !valid || Boolean(payment && !paymentError)} onPress={() => void settleDemoShare()} /> : null}<Button title="Open wallet" secondary onPress={() => router.push('/(tabs)/wallet')} /><Text style={{ color: C.muted, fontSize: 12, textAlign: 'center' }}>Creating a split is local-only. Demo settlement is clearly simulated and never submits an XRPL transaction.</Text>
  </Page>;
}
function Line({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ color: strong ? C.ink : C.muted, fontWeight: strong ? '800' : '500' }}>{label}</Text><Text style={{ color: C.ink, fontWeight: strong ? '900' : '700' }}>{value}</Text></View>; }
