import DateTimePicker from '@react-native-community/datetimepicker';
import * as Location from 'expo-location';
import MapView, { Marker } from 'react-native-maps';
import { useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Platform, Pressable, Text, View } from 'react-native';
import { Button, Card, Copy, Eyebrow, Field, Header, Heading, Notice, Page } from '@/components/ui';
import { C } from '@/constants/theme';
import { api } from '@/lib/api';
import { searchPlaces } from '@/services/places';
import type { PlaceResult, TripLocation } from '@/types';

type Itinerary = { origin?: { label?: string; lat?: number; lon?: number }; destination?: { label?: string; lat?: number; lon?: number }; legs?: Array<{ type?: string; route?: string | null; from?: { label?: string }; to?: { label?: string }; departure?: string; arrival?: string; duration_seconds?: number; live?: boolean }>; duration_seconds?: number; leave_at?: string; arrive_at?: string; arrive_by?: string; transfers?: number; routes?: string[]; summary?: string; live?: boolean; on_time?: boolean; slack_seconds?: number; alerts?: Array<{ header?: string; description?: string; routes?: string[] }>; mta_enrichment?: { fresh?: boolean; updated_at?: string | null; live_arrivals_available?: boolean } };
function tripPoint(point: TripLocation) { return { label: point.label, ...(point.latitude !== undefined && point.longitude !== undefined ? { lat: point.latitude, lon: point.longitude } : { query: point.label }) }; }
function clock(value?: string) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : date.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }); }

export default function NextStopScreen() {
  const [from, setFrom] = useState<TripLocation>({ label: '' }); const [to, setTo] = useState<TripLocation>({ label: '' });
  const [deadline, setDeadline] = useState(() => new Date(Date.now() + 90 * 60 * 1000)); const [picker, setPicker] = useState<'date' | 'time' | 'datetime' | null>(null);
  const [searchFor, setSearchFor] = useState<'from' | 'to' | null>(null); const [suggestions, setSuggestions] = useState<PlaceResult[]>([]); const [searchBusy, setSearchBusy] = useState(false); const [locBusy, setLocBusy] = useState(false); const searchRequest = useRef(0);
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [plan, setPlan] = useState<Itinerary | null>(null);
  const mapPoints = { origin: { latitude: plan?.origin?.lat ?? from.latitude, longitude: plan?.origin?.lon ?? from.longitude }, destination: { latitude: plan?.destination?.lat ?? to.latitude, longitude: plan?.destination?.lon ?? to.longitude } };
  const selected = useMemo(() => { const a = mapPoints.origin; const b = mapPoints.destination; if (a.latitude != null && a.longitude != null && b.latitude != null && b.longitude != null) return { latitude: (a.latitude + b.latitude) / 2, longitude: (a.longitude + b.longitude) / 2, latitudeDelta: Math.max(Math.abs(a.latitude - b.latitude) * 1.6, .03), longitudeDelta: Math.max(Math.abs(a.longitude - b.longitude) * 1.6, .03) }; return { latitude: a.latitude ?? b.latitude ?? 40.742, longitude: a.longitude ?? b.longitude ?? -73.99, latitudeDelta: .08, longitudeDelta: .08 }; }, [mapPoints.destination.latitude, mapPoints.destination.longitude, mapPoints.origin.latitude, mapPoints.origin.longitude]);
  async function findPlaces(target: 'from' | 'to', value: string) { setSearchFor(target); if (target === 'from') setFrom({ label: value }); else setTo({ label: value }); const request = ++searchRequest.current; if (value.trim().length < 2) { setSuggestions([]); setSearchBusy(false); return; } setSearchBusy(true); try { const results = await searchPlaces(value.trim()); if (request === searchRequest.current) setSuggestions(results); } catch { if (request === searchRequest.current) setSuggestions([]); } finally { if (request === searchRequest.current) setSearchBusy(false); } }
  async function useLocation() { setLocBusy(true); setError(''); try { const permission = await Location.requestForegroundPermissionsAsync(); if (!permission.granted) { setError('Location permission is off. You can enter an origin manually.'); return; } const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); const place = { label: 'Current location', latitude: position.coords.latitude, longitude: position.coords.longitude }; setFrom(place); setSearchFor(null); } catch { setError('Current location is unavailable. Enter an origin manually.'); } finally { setLocBusy(false); } }
  async function compare() { if (!from.label.trim() || !to.label.trim()) { setError('Add both an origin and destination to plan your trip.'); return; } if (deadline.getTime() <= Date.now()) { setError('Choose an arrival time in the future.'); return; } setLoading(true); setError(''); try { const result = await api<Itinerary>('/api/transit/plan', { method: 'POST', body: JSON.stringify({ origin: tripPoint(from), destination: tripPoint(to), arrive_by: deadline.toISOString() }) }); setPlan(result); } catch (e) { setError(e instanceof Error ? e.message : 'Transit planning is unavailable right now.'); setPlan(null); } finally { setLoading(false); } }
  function selectPlace(place: PlaceResult) { const value = { label: place.name, latitude: place.lat, longitude: place.lon, placeId: place.id }; if (searchFor === 'from') setFrom(value); else setTo(value); setSearchFor(null); setSuggestions([]); }
  function changeDeadline(event: { type: string }, date?: Date) { if (event.type === 'dismissed' || !date) { setPicker(null); return; } if (Platform.OS === 'android' && picker === 'date') { const next = new Date(deadline); next.setFullYear(date.getFullYear(), date.getMonth(), date.getDate()); setDeadline(next); setPicker('time'); return; } if (Platform.OS === 'android' && picker === 'time') { const next = new Date(deadline); next.setHours(date.getHours(), date.getMinutes(), 0, 0); setDeadline(next); setPicker(null); return; } setDeadline(date); setPicker(null); }
  return <Page><Header title="NextStop" /><Eyebrow>PLAN YOUR ARRIVAL</Eyebrow><Heading small>Make the city work for your day.</Heading><Copy>Set where you’re going and when you need to arrive.</Copy>
    {!plan ? <Card><Field label="FROM" value={from.label} onChangeText={(value) => void findPlaces('from', value)} placeholder="Search origin" /><Button title={locBusy ? 'Finding your location…' : 'Use my location'} secondary disabled={locBusy} onPress={() => void useLocation()} /><Field label="TO" value={to.label} onChangeText={(value) => void findPlaces('to', value)} placeholder="Search destination" />
      {(searchFor !== null && suggestions.length > 0) && <View style={{ borderWidth: 1, borderColor: C.line, borderRadius: 12, overflow: 'hidden', backgroundColor: 'white' }}>{suggestions.map((place) => <Pressable key={`${place.type}-${place.id}`} onPress={() => selectPlace(place)} style={{ padding: 13, borderBottomWidth: 1, borderBottomColor: C.line }}><Text style={{ color: C.ink, fontWeight: '700' }}>{place.name}</Text>{place.routes?.length ? <Text style={{ color: C.muted, marginTop: 3 }}>{place.routes.join(' · ')}</Text> : null}</Pressable>)}</View>}
      {searchBusy && <ActivityIndicator color={C.blue} />}
      {searchFor && <Text style={{ color: C.muted, fontSize: 12 }}>Search results appear when the place service finds a match. You can still use a manually typed address.</Text>}
      <View style={{ gap: 8 }}><Text style={{ color: C.ink, fontWeight: '800' }}>ARRIVE BY</Text><Pressable accessibilityRole="button" onPress={() => setPicker(Platform.OS === 'ios' ? 'datetime' : 'date')} style={{ backgroundColor: 'white', borderWidth: 1, borderColor: C.line, padding: 14, borderRadius: 12 }}><Text style={{ color: C.ink, fontSize: 16 }}>{deadline.toLocaleString([], { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</Text></Pressable>{picker && <DateTimePicker value={deadline} mode={picker} minimumDate={new Date()} onChange={changeDeadline} />}</View>
      <Button title={loading ? 'Finding transit…' : 'Compare routes'} disabled={loading} onPress={() => void compare()} />
    </Card> : <><Card>
      <Eyebrow>LEAVE BY</Eyebrow><Text style={{ color: C.ink, fontSize: 38, lineHeight: 42, fontWeight: '900' }}>{clock(plan.leave_at)}</Text>
      <Text style={{ color: C.muted, fontSize: 13 }}>to arrive by {clock(plan.arrive_by ?? deadline.toISOString())}</Text>
      <View style={{ borderTopWidth: 1, borderTopColor: C.line, paddingTop: 13, gap: 9 }}><Text style={{ color: C.ink, fontSize: 20, fontWeight: '800' }}>{plan.origin?.label ?? from.label} → {plan.destination?.label ?? to.label}</Text>{plan.routes?.length ? <View style={{ flexDirection: 'row', gap: 7, flexWrap: 'wrap' }}>{plan.routes.map((route) => <Text key={route} style={{ minWidth: 30, height: 30, paddingHorizontal: 8, paddingTop: 6, borderRadius: 15, overflow: 'hidden', textAlign: 'center', color: 'NQRW'.includes(route) ? C.ink : 'white', backgroundColor: routeColor(route), fontWeight: '900' }}>{route}</Text>)}</View> : null}<Text style={{ color: C.muted, lineHeight: 20 }}>{plan.summary ?? 'MTA transit itinerary'}</Text></View>
      <View style={{ flexDirection: 'row', gap: 20, flexWrap: 'wrap' }}><Metric label="ARRIVE" value={clock(plan.arrive_at)} /><Metric label="TRAVEL TIME" value={typeof plan.duration_seconds === 'number' ? `${Math.round(plan.duration_seconds / 60)} min` : '—'} /><Metric label="TRANSFERS" value={plan.transfers != null ? String(plan.transfers) : '—'} /></View>
      <Notice error={plan.on_time === false}>{plan.on_time === false ? 'This route may miss your selected arrival time.' : plan.mta_enrichment?.fresh && plan.mta_enrichment.live_arrivals_available ? 'Using current MTA arrival data where available.' : 'Live arrivals are unavailable; this plan uses the current schedule.'}</Notice>
      {plan.legs?.map((leg, i) => <View key={`${i}-${leg.route ?? leg.type}`} style={{ flexDirection: 'row', gap: 11, borderTopWidth: 1, borderTopColor: C.line, paddingTop: 11 }}><Text style={{ width: 56, color: C.blue, fontWeight: '900' }}>{leg.route ?? (leg.type === 'walk' ? 'WALK' : leg.type?.toUpperCase())}</Text><Text style={{ flex: 1, color: C.ink }}>{leg.from?.label ?? '—'} → {leg.to?.label ?? '—'}{leg.departure ? `\n${clock(leg.departure)} – ${clock(leg.arrival)}` : ''}{leg.live ? '\nLive timing' : ''}</Text></View>)}
      {plan.alerts?.map((alert, i) => <Notice key={i}>{alert.routes?.length ? `${alert.routes.join(', ')} · ` : ''}{alert.header ?? alert.description ?? 'Service alert'}</Notice>)}<Button title="Edit trip" secondary onPress={() => setPlan(null)} />
    </Card><Card><Eyebrow>OTHER MODES</Eyebrow>{(['Drive', 'Walk'] as const).map((mode) => <View key={mode} style={{ borderTopColor: C.line, borderTopWidth: 1, paddingTop: 11 }}><Text style={{ color: C.ink, fontWeight: '800' }}>{mode}</Text><Text style={{ color: C.muted, marginTop: 4 }}>Route comparison is unavailable in the current mobile API.</Text></View>)}</Card></>}
    {error ? <Notice error>{error}</Notice> : null}
    <Card style={{ padding: 0, overflow: 'hidden' }}><MapView style={{ height: 250 }} region={selected} showsUserLocation={false} accessibilityLabel="Trip map"><>{mapPoints.origin.latitude != null && mapPoints.origin.longitude != null ? <Marker coordinate={{ latitude: mapPoints.origin.latitude, longitude: mapPoints.origin.longitude }} title="Origin" description={plan?.origin?.label ?? from.label} pinColor={C.blue} /> : null}{mapPoints.destination.latitude != null && mapPoints.destination.longitude != null ? <Marker coordinate={{ latitude: mapPoints.destination.latitude, longitude: mapPoints.destination.longitude }} title="Destination" description={plan?.destination?.label ?? to.label} pinColor={C.red} /> : null}</></MapView></Card>
    <Text style={{ color: C.muted, fontSize: 12, textAlign: 'center' }}>Transit details come from ChatNYC’s current MTA planner. Google route comparison is not yet exposed to mobile.</Text>
  </Page>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={{ minWidth: 72, gap: 4 }}><Text style={{ color: C.muted, fontWeight: '800', fontSize: 10 }}>{label}</Text><Text style={{ color: C.ink, fontSize: 15, fontWeight: '800' }}>{value}</Text></View>; }
function routeColor(route: string) { if ('123'.includes(route)) return '#EE352E'; if ('456'.includes(route)) return '#00933C'; if ('7'.includes(route)) return '#B933AD'; if ('ACE'.includes(route)) return '#0039A6'; if ('BDFM'.includes(route)) return '#FF6319'; if ('NQRW'.includes(route)) return '#FCCC0A'; if ('G'.includes(route)) return '#6CBE45'; if ('JZ'.includes(route)) return '#996633'; if ('L'.includes(route)) return '#A7A9AC'; return C.ink; }
