import type { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Link } from 'expo-router';
import { C, radius } from '@/constants/theme';

export function Page({ children, scroll = true }: PropsWithChildren<{ scroll?: boolean }>) {
  const content = <View style={styles.content}>{children}</View>;
  return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.safe}>{scroll ? <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ flexGrow: 1 }}>{content}</ScrollView> : content}</View></SafeAreaView>;
}
export function Header({ title = 'ChatNYC' }: { title?: string }) { return <View style={styles.header}><Text style={styles.brand}>{title}</Text><Link href="/profile" asChild><Pressable accessibilityRole="button" accessibilityLabel="Open profile" style={styles.avatar}><Text style={styles.avatarText}>G</Text></Pressable></Link></View>; }
export function Eyebrow({ children }: PropsWithChildren) { return <Text style={styles.eyebrow}>{children}</Text>; }
export function Heading({ children, small = false }: PropsWithChildren<{ small?: boolean }>) { return <Text style={[styles.heading, small && { fontSize: 27, lineHeight: 32 }]}>{children}</Text>; }
export function Copy({ children }: PropsWithChildren) { return <Text style={styles.copy}>{children}</Text>; }
export function Card({ children, style }: PropsWithChildren<{ style?: object }>) { return <View style={[styles.card, style]}>{children}</View>; }
export function Button({ title, onPress, secondary = false, disabled = false, accessory }: { title: string; onPress: () => void; secondary?: boolean; disabled?: boolean; accessory?: ReactNode }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, secondary && styles.secondary, disabled && { opacity: .5 }, pressed && !disabled && { opacity: .8, transform: [{ scale: .985 }] }]}><Text style={[styles.buttonText, secondary && { color: C.ink }]}>{title}</Text>{accessory}</Pressable>; }
export function Field({ label, value, onChangeText, placeholder, multiline = false, keyboardType, autoCapitalize = 'sentences' }: { label: string; value: string; onChangeText: (value: string) => void; placeholder?: string; multiline?: boolean; keyboardType?: 'default' | 'decimal-pad' | 'email-address'; autoCapitalize?: 'none' | 'sentences' }) { return <View style={{ gap: 7 }}><Text style={styles.fieldLabel}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#92969b" multiline={multiline} keyboardType={keyboardType} autoCapitalize={autoCapitalize} style={[styles.field, multiline && { minHeight: 82, textAlignVertical: 'top' }]} /></View>; }
export function Notice({ children, error = false }: PropsWithChildren<{ error?: boolean }>) { return <Text accessibilityRole={error ? 'alert' : undefined} style={[styles.notice, error && { color: '#a32922', backgroundColor: '#fff0ed' }]}>{children}</Text>; }
export function Busy({ label = 'Loading…' }: { label?: string }) { return <View style={{ flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 12 }}><ActivityIndicator color={C.blue} /><Text style={{ color: C.muted }}>{label}</Text></View>; }
export const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, content: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingHorizontal: 20, paddingBottom: 28, gap: 18 }, header: { height: 56, marginBottom: 9, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, brand: { fontSize: 19, color: C.ink, fontWeight: '900', letterSpacing: -.5 }, avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.ink, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: 'white', fontWeight: '700' }, eyebrow: { color: C.blue, letterSpacing: 1.3, fontSize: 11, fontWeight: '800' }, heading: { color: C.ink, fontSize: 36, lineHeight: 40, fontWeight: '800', letterSpacing: -1.1 }, copy: { color: C.muted, fontSize: 15, lineHeight: 22 }, card: { padding: 17, backgroundColor: C.paper, borderColor: C.line, borderWidth: 1, borderRadius: radius.card, gap: 13 }, button: { minHeight: 50, paddingHorizontal: 16, borderRadius: radius.button, backgroundColor: C.blue, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, secondary: { backgroundColor: C.paper, borderColor: C.line, borderWidth: 1 }, buttonText: { color: 'white', fontSize: 15, fontWeight: "700" }, fieldLabel: { color: '#34383d', fontSize: 12, fontWeight: '800', letterSpacing: .7 }, field: { minHeight: 50, borderWidth: 1, borderColor: C.line, backgroundColor: C.paper, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, color: C.ink, fontSize: 16 }, notice: { overflow: 'hidden', color: C.muted, backgroundColor: C.soft, padding: 12, borderRadius: 11, fontSize: 13, lineHeight: 18 } });
